#!/usr/bin/env python3
"""seed_configuration.py — Sync the runtime cache from the authored YAML (R-08, §236).

Reads the authored sources of truth:
  configuration/*.yaml         -> configuration.configuration / configuration.providers
  prompts/registry.yaml        -> configuration.prompt_registry
  prompts/*/PR-*.yaml          -> configuration.prompt_versions   (prompt BODIES)
  workflows/registry.yaml      -> configuration.workflow_registry
  configuration retrieval.authoritySources -> configuration.authority_sources
  database/seeds/knowledge_categories.yaml -> configuration.knowledge_categories
  database/seeds/dictionaries.yaml         -> configuration.synonyms / acronyms

Emits idempotent SQL to stdout (or --apply to execute against $DATABASE_URL when a
driver is available). This is the mechanism by which ALL user-adjustable behavior is
configured without editing source: edit the YAML, re-run the seed. No value is
authored directly in the tables (§627).
"""
import argparse, glob, json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def load_yaml(path):
    import yaml
    with open(path) as fh:
        return yaml.safe_load(fh) or {}


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def jq(obj):
    """JSONB literal, or NULL when the key is absent in the authored YAML."""
    if obj is None:
        return "NULL"
    return "'" + json.dumps(obj).replace("'", "''") + "'::jsonb"


def emit():
    import yaml
    out = []
    out.append("-- Generated by seed_configuration.py from authored YAML (R-08). Idempotent.")
    out.append("BEGIN;")

    # configuration.configuration (flatten each domain file to dotted keys)
    merged = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "configuration", "*.yaml"))):
        data = load_yaml(path)
        for domain, body in data.items():
            merged[domain] = body

    def flatten(prefix, obj, rows):
        if isinstance(obj, dict):
            for k, v in obj.items():
                flatten(f"{prefix}.{k}" if prefix else k, v, rows)
        else:
            rows.append((prefix, obj))

    for domain, body in merged.items():
        rows = []
        flatten(domain, body, rows)
        for key, val in rows:
            out.append(
                "INSERT INTO configuration.configuration (domain, key, value) VALUES "
                f"({q(domain)}, {q(key)}, {q(json.dumps(val))}::jsonb) "
                "ON CONFLICT (domain, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();"
            )

    # configuration.providers (from providers.yaml top-level provider kinds)
    providers = load_yaml(os.path.join(ROOT, "configuration", "providers.yaml"))
    for kind in ("ocr", "llm", "embedding", "storage"):
        if kind in providers:
            out.append(
                "INSERT INTO configuration.providers (kind, settings) VALUES "
                f"({q(kind)}, {q(json.dumps(providers[kind]))}::jsonb) "
                "ON CONFLICT (kind) DO UPDATE SET settings = EXCLUDED.settings, updated_at = now();"
            )

    # authority sources (from retrieval.yaml)
    retr = load_yaml(os.path.join(ROOT, "configuration", "retrieval.yaml"))
    for a in (retr.get("authoritySources") or []):
        out.append(
            "INSERT INTO configuration.authority_sources (source, score) VALUES "
            f"({q(a['source'])}, {int(a['score'])}) "
            "ON CONFLICT (source) DO UPDATE SET score = EXCLUDED.score;"
        )

    # knowledge categories
    cats = load_yaml(os.path.join(ROOT, "database", "seeds", "knowledge_categories.yaml"))
    for c in (cats.get("categories") or []):
        out.append(
            "INSERT INTO configuration.knowledge_categories (category) VALUES "
            f"({q(c)}) ON CONFLICT (category) DO NOTHING;"
        )

    # dictionaries
    dic = load_yaml(os.path.join(ROOT, "database", "seeds", "dictionaries.yaml"))
    for s in (dic.get("synonyms") or []):
        out.append(
            "INSERT INTO configuration.synonyms (term, synonym) VALUES "
            f"({q(s['term'])}, {q(s['synonym'])}) ON CONFLICT (term, synonym) DO NOTHING;"
        )
    for a in (dic.get("acronyms") or []):
        out.append(
            "INSERT INTO configuration.acronyms (acronym, expansion) VALUES "
            f"({q(a['acronym'])}, {q(a['expansion'])}) ON CONFLICT (acronym, expansion) DO NOTHING;"
        )

    # prompt registry manifest
    preg = load_yaml(os.path.join(ROOT, "prompts", "registry.yaml"))
    for p in (preg.get("prompts") or []):
        ver = p.get("latestVersion")
        ver_sql = q(ver) if ver is not None else "NULL"
        out.append(
            "INSERT INTO configuration.prompt_registry (prompt_id, version, name, category, latest) VALUES "
            f"({q(p['id'])}, {ver_sql}, {q(p['name'])}, {q(p['category'])}, {str(ver is not None).lower()}) "
            "ON CONFLICT (prompt_id, version) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category;"
        )

    # prompt bodies (configuration.prompt_versions) — the runtime cache SW-007/SW-008 read.
    # Source of truth: prompts/<category>/PR-*.yaml (§175, §608, §612). Bodies are authored in
    # their owning sprint and are absent until then; only authored bodies are seeded.
    for path in sorted(glob.glob(os.path.join(ROOT, "prompts", "*", "PR-*.yaml"))):
        pv = load_yaml(path)
        pid, ver, body = pv.get("promptId"), pv.get("version"), pv.get("body")
        if not pid or not ver:
            print(f"skip {os.path.basename(path)}: missing promptId/version", file=sys.stderr)
            continue
        if not body:
            print(f"skip {pid}: body not authored yet", file=sys.stderr)
            continue
        # body carries the {{var}} placeholders and is the USER prompt; the YAML authors no
        # separate system prompt, so system_prompt stays NULL (SW-007/008 tolerate this).
        out.append(
            "INSERT INTO configuration.prompt_versions "
            "(prompt_id, version, system_prompt, user_prompt, schema, model_settings) VALUES "
            f"({q(pid)}, {q(ver)}, NULL, {q(body)}, "
            f"{jq(pv.get('outputContract'))}, {jq(pv.get('model'))}) "
            "ON CONFLICT (prompt_id, version) DO UPDATE SET "
            "system_prompt = EXCLUDED.system_prompt, user_prompt = EXCLUDED.user_prompt, "
            "schema = EXCLUDED.schema, model_settings = EXCLUDED.model_settings;"
        )

    # workflow registry
    wreg = load_yaml(os.path.join(ROOT, "workflows", "registry.yaml"))
    for section, wtype in (("master", "master"), ("shared", "shared"), ("utilities", "utility")):
        for w in (wreg.get(section) or []):
            out.append(
                "INSERT INTO configuration.workflow_registry (workflow_id, name, type, status, owned_by_sprint) VALUES "
                f"({q(w['id'])}, {q(w['name'])}, {q(wtype)}, {q(w['status'])}, {int(w['ownedBySprint'])}) "
                "ON CONFLICT (workflow_id) DO UPDATE SET name = EXCLUDED.name, type = EXCLUDED.type, "
                "status = EXCLUDED.status, owned_by_sprint = EXCLUDED.owned_by_sprint, updated_at = now();"
            )

    out.append("COMMIT;")

    # Post-seed sanity check (§236). Emitted after COMMIT so it reports what actually landed.
    # A fresh deployment that silently seeds zero prompt bodies is the exact failure this
    # bootstrap exists to prevent, so the seed step ends by showing the registry contents.
    out.append("")
    out.append("-- ---- post-seed verification ----")
    out.append("\\echo '== configuration.prompt_versions (bodies loaded) =='")
    out.append("SELECT prompt_id, version, "
               "(system_prompt IS NOT NULL) AS has_system, "
               "(user_prompt IS NOT NULL) AS has_user, "
               "length(user_prompt) AS user_prompt_len "
               "FROM configuration.prompt_versions ORDER BY prompt_id, version;")
    out.append("\\echo '== seeded row counts =='")
    out.append(
        "SELECT 'prompt_versions' AS table, count(*) AS rows FROM configuration.prompt_versions "
        "UNION ALL SELECT 'prompt_registry',   count(*) FROM configuration.prompt_registry "
        "UNION ALL SELECT 'providers',         count(*) FROM configuration.providers "
        "UNION ALL SELECT 'configuration',     count(*) FROM configuration.configuration "
        "UNION ALL SELECT 'workflow_registry', count(*) FROM configuration.workflow_registry "
        "ORDER BY 1;"
    )
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="execute against $DATABASE_URL (needs psycopg)")
    args = ap.parse_args()
    sql = emit()
    if args.apply:
        try:
            import psycopg  # noqa
        except Exception:
            print("psycopg not available; cannot --apply here. Emitting SQL instead.\n", file=sys.stderr)
            print(sql); sys.exit(0)
        dsn = os.environ.get("DATABASE_URL")
        if not dsn:
            print("DATABASE_URL not set", file=sys.stderr); sys.exit(2)
        with psycopg.connect(dsn) as conn:
            with conn.cursor() as cur:
                cur.execute(sql)
        print("seed applied")
    else:
        print(sql)


if __name__ == "__main__":
    main()
