-- 0008_retrieval_chunks.sql — repository.retrieval_chunks (§225).
-- Chunks are owned by Repository (generated by Ingestion, consumed by Retrieval) (R-13).
CREATE TABLE IF NOT EXISTS repository.retrieval_chunks (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    knowledge_unit_id UUID NOT NULL,
    chunk_order       INTEGER NOT NULL,
    content           TEXT NOT NULL,
    token_count       INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_retrieval_chunks_knowledge_units
        FOREIGN KEY (knowledge_unit_id) REFERENCES repository.knowledge_units (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_retrieval_chunks_knowledge_unit_id ON repository.retrieval_chunks (knowledge_unit_id);
CREATE INDEX IF NOT EXISTS idx_retrieval_chunks_chunk_order       ON repository.retrieval_chunks (chunk_order);
